# Generated by Django 4.2.7 on 2023-11-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts_app', '0002_audiofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
